using System.Globalization;

namespace Baykar.Shared.Localization;

public sealed class LocalizationService
{
    private static readonly IReadOnlyDictionary<SupportedLanguage, IReadOnlyDictionary<string, string>> Translations =
        new Dictionary<SupportedLanguage, IReadOnlyDictionary<string, string>>
        {
            [SupportedLanguage.English] = new Dictionary<string, string>
            {
                ["Common.Language"] = "Language",
                ["Common.English"] = "English",
                ["Common.Turkish"] = "Türkçe",
                ["Common.SelectedProtocol"] = "Selected Protocol:",
                ["Common.LocalPort"] = "Local Port:",
                ["Common.RemotePort"] = "Remote Port:",
                ["Common.ValidPacketCount"] = "Valid Packet Count:",
                ["Common.InvalidPacketCount"] = "Invalid Packet Count:",
                ["Common.Stopped"] = "Stopped",
                ["Common.Running"] = "Running",
                ["Common.None"] = "None",
                ["Common.ListeningOnPort"] = "Listening on port {0}",
                ["Common.ListenerError"] = "Listener error: {0}",
                ["Common.PacketParseError"] = "Packet parse error: {0}",
                ["Common.PayloadParseError"] = "Payload parse error: {0}",
                ["Common.Valid"] = "Valid.",
                ["Common.Invalid"] = "Invalid - {0}",

                ["User.WindowTitle"] = "Baykar User Interface",
                ["User.HeaderTitle"] = "Baykar User Interface",
                ["User.HeaderSubtitle"] = "Operator panel for communication packet monitoring",
                ["User.ConnectionStatusPanel"] = "Connection Status Panel",
                ["User.ConnectionStatus"] = "Connection Status:",
                ["User.NotConnected"] = "Not Connected",
                ["User.ListenerStatus"] = "Listener Status:",
                ["User.StartListener"] = "Start Listener",
                ["User.StopListener"] = "Stop Listener",
                ["User.PacketCountersPanel"] = "Packet Counters Panel",
                ["User.CommunicationPacket1Panel"] = "Communication Packet 1 Panel",
                ["User.CommunicationPacket2Panel"] = "Communication Packet 2 Panel",
                ["User.CommandPanel"] = "Command Panel",
                ["User.SendCommand1"] = "Send Command 1",
                ["User.SendCommand2"] = "Send Command 2",
                ["User.SendCommand3"] = "Send Command 3",
                ["User.Command1"] = "Command 1",
                ["User.Command2"] = "Command 2",
                ["User.Command3"] = "Command 3",
                ["User.FeedbackPanel"] = "Feedback Panel",
                ["User.LastReceivedFeedback"] = "Last Received Feedback:",
                ["User.LastAction"] = "Last Action:",
                ["User.SettingsPanel"] = "Settings Panel",
                ["User.Setting1"] = "Setting 1:",
                ["User.Setting2"] = "Setting 2:",
                ["User.Setting3"] = "Setting 3:",
                ["User.Setting4"] = "Setting 4:",
                ["User.Setting1Name"] = "Setting 1",
                ["User.Setting2Name"] = "Setting 2",
                ["User.Setting3Name"] = "Setting 3",
                ["User.Setting4Name"] = "Setting 4",
                ["User.SendSetting1"] = "Send Setting 1",
                ["User.SendSetting2"] = "Send Setting 2",
                ["User.SendSetting3"] = "Send Setting 3",
                ["User.SendSetting4"] = "Send Setting 4",
                ["User.BuiltPacketPanel"] = "Built Packet Panel",
                ["User.LastBuiltPacketType"] = "Last Built Packet Type:",
                ["User.LastBuiltPayloadLength"] = "Last Built Payload Length:",
                ["User.LastBuiltCrc"] = "Last Built CRC:",
                ["User.LastBuiltPacketBytes"] = "Last Built Packet Bytes:",
                ["User.ValidateLastBuiltPacket"] = "Validate Last Built Packet",
                ["User.ReceivedPacketPanel"] = "Received Packet Panel",
                ["User.LastReceivedPacketType"] = "Last Received Packet Type:",
                ["User.LastReceivedPacketBytes"] = "Last Received Packet Bytes:",
                ["User.ReceivedPacketDetails"] = "Received Packet Details",
                ["User.CommunicationPacket1ReceivedCount"] = "Communication Packet 1 Received Count:",
                ["User.CommunicationPacket1LastReceivedAt"] = "Communication Packet 1 Last Received At:",
                ["User.CommunicationPacket1LastBytes"] = "Communication Packet 1 Last Bytes:",
                ["User.CommunicationPacket2ReceivedCount"] = "Communication Packet 2 Received Count:",
                ["User.CommunicationPacket2LastReceivedAt"] = "Communication Packet 2 Last Received At:",
                ["User.CommunicationPacket2LastBytes"] = "Communication Packet 2 Last Bytes:",
                ["User.LogPanel"] = "Log Panel",
                ["User.LoggingStatus"] = "Logging Status:",
                ["User.CurrentLogFilePath"] = "Current Log File Path:",
                ["User.PlaybackStatus"] = "Playback Status:",
                ["User.SelectedPlaybackFilePath"] = "Selected Playback File Path:",
                ["User.MatlabConversionStatus"] = "MATLAB Conversion Status:",
                ["User.MatlabOutputFilePath"] = "MATLAB Output File Path:",
                ["User.StartLogging"] = "Start Logging",
                ["User.StopLogging"] = "Stop Logging",
                ["User.PlayLog"] = "Play Log",
                ["User.StopPlayback"] = "Stop Playback",
                ["User.ConvertToMatlab"] = "Convert to MATLAB",
                ["User.NoActionYet"] = "No action yet",
                ["User.NoFeedbackReceivedYet"] = "No feedback received yet",
                ["User.ListenerAlreadyRunning"] = "Listener is already running.",
                ["User.LoggingStarted"] = "Logging started",
                ["User.LoggingStopped"] = "Logging stopped",
                ["User.LoggingError"] = "Logging error: {0}",
                ["User.PlaybackAlreadyRunning"] = "Playback is already running",
                ["User.NoLogFileFound"] = "No log file found",
                ["User.NoRecordsFound"] = "No records found",
                ["User.PlayingProgress"] = "Playing {0}/{1}",
                ["User.PlaybackCompleted"] = "Playback completed",
                ["User.PlaybackStopped"] = "Playback stopped",
                ["User.PlaybackError"] = "Playback error: {0}",
                ["User.NotConverted"] = "Not converted",
                ["User.NoLogFileFoundToConvert"] = "No log file found to convert",
                ["User.ConversionStarted"] = "Conversion started",
                ["User.ConversionCompleted"] = "Conversion completed",
                ["User.ConversionFailed"] = "Conversion failed: {0}",
                ["User.ConversionError"] = "Conversion error: {0}",
                ["User.MatlabConversionCompletedAction"] = "MATLAB conversion completed",
                ["User.MatlabConversionFailedAction"] = "MATLAB conversion failed",
                ["User.CommandPacketSent"] = "{0} packet sent",
                ["User.CommandPacketSendFailed"] = "{0} packet send failed: {1}",
                ["User.SettingValueInvalid"] = "{0} value must be a valid number.",
                ["User.SettingPacketSent"] = "{0} packet sent",
                ["User.SettingPacketSendFailed"] = "{0} packet send failed: {1}",
                ["User.NoBuiltPacketForValidation"] = "No built packet is available for validation.",
                ["User.LastBuiltPacketValid"] = "Last built {0} packet is valid.",
                ["User.LastBuiltPacketInvalid"] = "Last built packet is invalid: {0}",

                ["Simulation.WindowTitle"] = "Baykar Simulation Interface",
                ["Simulation.HeaderTitle"] = "Baykar Simulation Interface",
                ["Simulation.HeaderSubtitle"] = "Simulated avionics unit monitor",
                ["Simulation.StatusPanel"] = "Simulation Status Panel",
                ["Simulation.SimulationStatus"] = "Simulation Status:",
                ["Simulation.ListenerStatus"] = "Listener Status:",
                ["Simulation.TransmissionPanel"] = "Transmission Panel",
                ["Simulation.CommunicationPacket1SentCount"] = "Communication Packet 1 Sent Count:",
                ["Simulation.CommunicationPacket2SentCount"] = "Communication Packet 2 Sent Count:",
                ["Simulation.SystemTime"] = "System Time:",
                ["Simulation.ReceivedCommandPanel"] = "Received Command Panel",
                ["Simulation.LastReceivedCommand"] = "Last Received Command:",
                ["Simulation.ReceivedSettingPanel"] = "Received Setting Panel",
                ["Simulation.LastReceivedSetting"] = "Last Received Setting:",
                ["Simulation.LastSettingValue"] = "Last Setting Value:",
                ["Simulation.FeedbackPanel"] = "Feedback Panel",
                ["Simulation.LastSentFeedback"] = "Last Sent Feedback:",
                ["Simulation.ControlButtons"] = "Control Buttons",
                ["Simulation.StartSimulation"] = "Start Simulation",
                ["Simulation.StopSimulation"] = "Stop Simulation",
                ["Simulation.ResetCounters"] = "Reset Counters",
                ["Simulation.BuiltCommunicationPackets"] = "Built Communication Packets",
                ["Simulation.LastBuiltCommunicationPacket1Bytes"] = "Last Built Communication Packet 1 Bytes:",
                ["Simulation.LastBuiltCommunicationPacket2Bytes"] = "Last Built Communication Packet 2 Bytes:",
                ["Simulation.ValidateLastBuiltPackets"] = "Validate Last Built Packets",
                ["Simulation.ValidationResult"] = "Validation Result:",
                ["Simulation.LastReceivedPacketBytes"] = "Last Received Packet Bytes:",
                ["Simulation.ParserError"] = "Parser Error:",
                ["Simulation.NoParserErrors"] = "No parser errors",
                ["Simulation.NoPacketValidationYet"] = "No packet validation yet",
                ["Simulation.TransmissionError"] = "Transmission error: {0}",
                ["Simulation.NoBuiltPacketsForValidation"] = "No built communication packets are available for validation.",
                ["Simulation.BothBuiltPacketsValid"] = "Both built communication packets are valid.",
                ["Simulation.PacketValidationPair"] = "Packet 1: {0} Packet 2: {1}",
                ["Simulation.FeedbackSendFailed"] = "Feedback send failed: {0}",

                ["Automation.Script"] = "Script",
                ["Automation.Attaching"] = "Attaching to Baykar.UserInterface...",
                ["Automation.MainWindowNotFound"] = "Baykar.UserInterface main window was not found.",
                ["Automation.AttachedWindowTitle"] = "Attached window title: {0}",
                ["Automation.DefaultScriptNotFoundPrompt"] = "Default test script was not found. Enter test script path: ",
                ["Automation.ScriptPathRequired"] = "Test script path is required.",
                ["Automation.UserInterfaceNotRunning"] = "Baykar.UserInterface is not running. Start it before running automation tests.",
                ["Automation.Test"] = "Test",
                ["Automation.Pass"] = "PASS",
                ["Automation.Fail"] = "FAIL",
                ["Automation.FinalResult"] = "Final Result",
                ["Automation.Passed"] = "PASSED",
                ["Automation.Failed"] = "FAILED",
                ["Automation.PdfReport"] = "PDF Report",
                ["Automation.PdfReportFailed"] = "PDF report generation failed: {0}",
                ["Automation.StepCompleted"] = "Step completed.",
                ["Automation.ExpectedTextFound"] = "Expected text was found.",
                ["Automation.TextWasNotEmpty"] = "Text was not empty.",
                ["Automation.NumericValueGreater"] = "Numeric value was greater than expected.",
                ["Automation.UnsupportedAction"] = "Unsupported action: {0}",
                ["Automation.RequiredProperty"] = "{0} is required.",
                ["Automation.ElementToExist"] = "element to exist",
                ["Automation.NotFound"] = "not found",
                ["Automation.NonEmptyText"] = "non-empty text",
                ["Automation.NotNumericActual"] = "not numeric; text='{0}'",
                ["Automation.FailureMessage"] = "Step='{0}', AutomationId='{1}', Expected='{2}', Actual='{3}', TimeoutMs={4}.",
                ["AutomationStep.Default User Interface Automation Test"] = "Default User Interface Automation Test",
                ["AutomationStep.Start user interface listener"] = "Start user interface listener",
                ["AutomationStep.Wait for Communication Packet 1 count"] = "Wait for Communication Packet 1 count",
                ["AutomationStep.Wait for Communication Packet 2 count"] = "Wait for Communication Packet 2 count",
                ["AutomationStep.Send Command 1 and verify feedback"] = "Send Command 1 and verify feedback",
                ["AutomationStep.Send Setting 1 and verify feedback"] = "Send Setting 1 and verify feedback",
                ["AutomationStep.Send Command 1"] = "Send Command 1",
                ["AutomationStep.Send Setting 1"] = "Send Setting 1",
                ["AutomationStep.Start logging"] = "Start logging",
                ["AutomationStep.Stop logging"] = "Stop logging",

                ["Report.Title"] = "UI Automation Test Report",
                ["Report.TestName"] = "Test name",
                ["Report.StartTime"] = "Start time",
                ["Report.FinishTime"] = "Finish time",
                ["Report.Duration"] = "Duration",
                ["Report.FinalResult"] = "Final result",
                ["Report.StepResults"] = "Step Results",
                ["Report.Step"] = "Step",
                ["Report.Result"] = "Result",
                ["Report.Message"] = "Message",
                ["Report.Passed"] = "Passed",
                ["Report.Failed"] = "Failed"
            },
            [SupportedLanguage.Turkish] = new Dictionary<string, string>
            {
                ["Common.Language"] = "Dil",
                ["Common.English"] = "English",
                ["Common.Turkish"] = "Türkçe",
                ["Common.SelectedProtocol"] = "Seçilen Protokol:",
                ["Common.LocalPort"] = "Yerel Port:",
                ["Common.RemotePort"] = "Uzak Port:",
                ["Common.ValidPacketCount"] = "Geçerli Paket Sayısı:",
                ["Common.InvalidPacketCount"] = "Geçersiz Paket Sayısı:",
                ["Common.Stopped"] = "Durduruldu",
                ["Common.Running"] = "Çalışıyor",
                ["Common.None"] = "Yok",
                ["Common.ListeningOnPort"] = "{0} portu dinleniyor",
                ["Common.ListenerError"] = "Dinleyici hatası: {0}",
                ["Common.PacketParseError"] = "Paket ayrıştırma hatası: {0}",
                ["Common.PayloadParseError"] = "Yük ayrıştırma hatası: {0}",
                ["Common.Valid"] = "Geçerli.",
                ["Common.Invalid"] = "Geçersiz - {0}",

                ["User.WindowTitle"] = "Baykar Kullanıcı Arayüzü",
                ["User.HeaderTitle"] = "Baykar Kullanıcı Arayüzü",
                ["User.HeaderSubtitle"] = "Haberleşme paketi izleme için operatör paneli",
                ["User.ConnectionStatusPanel"] = "Bağlantı Durumu Paneli",
                ["User.ConnectionStatus"] = "Bağlantı Durumu:",
                ["User.NotConnected"] = "Bağlı Değil",
                ["User.ListenerStatus"] = "Dinleyici Durumu:",
                ["User.StartListener"] = "Dinleyiciyi Başlat",
                ["User.StopListener"] = "Dinleyiciyi Durdur",
                ["User.PacketCountersPanel"] = "Paket Sayaçları Paneli",
                ["User.CommunicationPacket1Panel"] = "Haberleşme Paketi 1 Paneli",
                ["User.CommunicationPacket2Panel"] = "Haberleşme Paketi 2 Paneli",
                ["User.CommandPanel"] = "Komut Paneli",
                ["User.SendCommand1"] = "Komut 1 Gönder",
                ["User.SendCommand2"] = "Komut 2 Gönder",
                ["User.SendCommand3"] = "Komut 3 Gönder",
                ["User.Command1"] = "Komut 1",
                ["User.Command2"] = "Komut 2",
                ["User.Command3"] = "Komut 3",
                ["User.FeedbackPanel"] = "Geri Besleme Paneli",
                ["User.LastReceivedFeedback"] = "Son Alınan Geri Besleme:",
                ["User.LastAction"] = "Son İşlem:",
                ["User.SettingsPanel"] = "Ayarlar Paneli",
                ["User.Setting1"] = "Ayar 1:",
                ["User.Setting2"] = "Ayar 2:",
                ["User.Setting3"] = "Ayar 3:",
                ["User.Setting4"] = "Ayar 4:",
                ["User.Setting1Name"] = "Ayar 1",
                ["User.Setting2Name"] = "Ayar 2",
                ["User.Setting3Name"] = "Ayar 3",
                ["User.Setting4Name"] = "Ayar 4",
                ["User.SendSetting1"] = "Ayar 1 Gönder",
                ["User.SendSetting2"] = "Ayar 2 Gönder",
                ["User.SendSetting3"] = "Ayar 3 Gönder",
                ["User.SendSetting4"] = "Ayar 4 Gönder",
                ["User.BuiltPacketPanel"] = "Oluşturulan Paket Paneli",
                ["User.LastBuiltPacketType"] = "Son Oluşturulan Paket Türü:",
                ["User.LastBuiltPayloadLength"] = "Son Oluşturulan Yük Uzunluğu:",
                ["User.LastBuiltCrc"] = "Son Oluşturulan CRC:",
                ["User.LastBuiltPacketBytes"] = "Son Oluşturulan Paket Baytları:",
                ["User.ValidateLastBuiltPacket"] = "Son Oluşturulan Paketi Doğrula",
                ["User.ReceivedPacketPanel"] = "Alınan Paket Paneli",
                ["User.LastReceivedPacketType"] = "Son Alınan Paket Türü:",
                ["User.LastReceivedPacketBytes"] = "Son Alınan Paket Baytları:",
                ["User.ReceivedPacketDetails"] = "Alınan Paket Detayları",
                ["User.CommunicationPacket1ReceivedCount"] = "Haberleşme Paketi 1 Alınma Sayısı:",
                ["User.CommunicationPacket1LastReceivedAt"] = "Haberleşme Paketi 1 Son Alınma Zamanı:",
                ["User.CommunicationPacket1LastBytes"] = "Haberleşme Paketi 1 Son Baytları:",
                ["User.CommunicationPacket2ReceivedCount"] = "Haberleşme Paketi 2 Alınma Sayısı:",
                ["User.CommunicationPacket2LastReceivedAt"] = "Haberleşme Paketi 2 Son Alınma Zamanı:",
                ["User.CommunicationPacket2LastBytes"] = "Haberleşme Paketi 2 Son Baytları:",
                ["User.LogPanel"] = "Log Paneli",
                ["User.LoggingStatus"] = "Loglama Durumu:",
                ["User.CurrentLogFilePath"] = "Geçerli Log Dosya Yolu:",
                ["User.PlaybackStatus"] = "Oynatma Durumu:",
                ["User.SelectedPlaybackFilePath"] = "Seçilen Oynatma Dosya Yolu:",
                ["User.MatlabConversionStatus"] = "MATLAB Dönüşüm Durumu:",
                ["User.MatlabOutputFilePath"] = "MATLAB Çıktı Dosya Yolu:",
                ["User.StartLogging"] = "Loglamayı Başlat",
                ["User.StopLogging"] = "Loglamayı Durdur",
                ["User.PlayLog"] = "Logu Oynat",
                ["User.StopPlayback"] = "Oynatmayı Durdur",
                ["User.ConvertToMatlab"] = "MATLAB'a Dönüştür",
                ["User.NoActionYet"] = "Henüz işlem yok",
                ["User.NoFeedbackReceivedYet"] = "Henüz geri besleme alınmadı",
                ["User.ListenerAlreadyRunning"] = "Dinleyici zaten çalışıyor.",
                ["User.LoggingStarted"] = "Loglama başladı",
                ["User.LoggingStopped"] = "Loglama durduruldu",
                ["User.LoggingError"] = "Loglama hatası: {0}",
                ["User.PlaybackAlreadyRunning"] = "Oynatma zaten çalışıyor",
                ["User.NoLogFileFound"] = "Log dosyası bulunamadı",
                ["User.NoRecordsFound"] = "Kayıt bulunamadı",
                ["User.PlayingProgress"] = "Oynatılıyor {0}/{1}",
                ["User.PlaybackCompleted"] = "Oynatma tamamlandı",
                ["User.PlaybackStopped"] = "Oynatma durduruldu",
                ["User.PlaybackError"] = "Oynatma hatası: {0}",
                ["User.NotConverted"] = "Dönüştürülmedi",
                ["User.NoLogFileFoundToConvert"] = "Dönüştürülecek log dosyası bulunamadı",
                ["User.ConversionStarted"] = "Dönüşüm başladı",
                ["User.ConversionCompleted"] = "Dönüşüm tamamlandı",
                ["User.ConversionFailed"] = "Dönüşüm başarısız: {0}",
                ["User.ConversionError"] = "Dönüşüm hatası: {0}",
                ["User.MatlabConversionCompletedAction"] = "MATLAB dönüşümü tamamlandı",
                ["User.MatlabConversionFailedAction"] = "MATLAB dönüşümü başarısız",
                ["User.CommandPacketSent"] = "{0} paketi gönderildi",
                ["User.CommandPacketSendFailed"] = "{0} paketi gönderilemedi: {1}",
                ["User.SettingValueInvalid"] = "{0} değeri geçerli bir sayı olmalıdır.",
                ["User.SettingPacketSent"] = "{0} paketi gönderildi",
                ["User.SettingPacketSendFailed"] = "{0} paketi gönderilemedi: {1}",
                ["User.NoBuiltPacketForValidation"] = "Doğrulama için oluşturulmuş paket yok.",
                ["User.LastBuiltPacketValid"] = "Son oluşturulan {0} paketi geçerli.",
                ["User.LastBuiltPacketInvalid"] = "Son oluşturulan paket geçersiz: {0}",

                ["Simulation.WindowTitle"] = "Baykar Simülasyon Arayüzü",
                ["Simulation.HeaderTitle"] = "Baykar Simülasyon Arayüzü",
                ["Simulation.HeaderSubtitle"] = "Simüle edilmiş aviyonik birim izleyicisi",
                ["Simulation.StatusPanel"] = "Simülasyon Durumu Paneli",
                ["Simulation.SimulationStatus"] = "Simülasyon Durumu:",
                ["Simulation.ListenerStatus"] = "Dinleyici Durumu:",
                ["Simulation.TransmissionPanel"] = "Aktarım Paneli",
                ["Simulation.CommunicationPacket1SentCount"] = "Haberleşme Paketi 1 Gönderim Sayısı:",
                ["Simulation.CommunicationPacket2SentCount"] = "Haberleşme Paketi 2 Gönderim Sayısı:",
                ["Simulation.SystemTime"] = "Sistem Zamanı:",
                ["Simulation.ReceivedCommandPanel"] = "Alınan Komut Paneli",
                ["Simulation.LastReceivedCommand"] = "Son Alınan Komut:",
                ["Simulation.ReceivedSettingPanel"] = "Alınan Ayar Paneli",
                ["Simulation.LastReceivedSetting"] = "Son Alınan Ayar:",
                ["Simulation.LastSettingValue"] = "Son Ayar Değeri:",
                ["Simulation.FeedbackPanel"] = "Geri Besleme Paneli",
                ["Simulation.LastSentFeedback"] = "Son Gönderilen Geri Besleme:",
                ["Simulation.ControlButtons"] = "Kontrol Düğmeleri",
                ["Simulation.StartSimulation"] = "Simülasyonu Başlat",
                ["Simulation.StopSimulation"] = "Simülasyonu Durdur",
                ["Simulation.ResetCounters"] = "Sayaçları Sıfırla",
                ["Simulation.BuiltCommunicationPackets"] = "Oluşturulan Haberleşme Paketleri",
                ["Simulation.LastBuiltCommunicationPacket1Bytes"] = "Son Oluşturulan Haberleşme Paketi 1 Baytları:",
                ["Simulation.LastBuiltCommunicationPacket2Bytes"] = "Son Oluşturulan Haberleşme Paketi 2 Baytları:",
                ["Simulation.ValidateLastBuiltPackets"] = "Son Oluşturulan Paketleri Doğrula",
                ["Simulation.ValidationResult"] = "Doğrulama Sonucu:",
                ["Simulation.LastReceivedPacketBytes"] = "Son Alınan Paket Baytları:",
                ["Simulation.ParserError"] = "Ayrıştırıcı Hatası:",
                ["Simulation.NoParserErrors"] = "Ayrıştırıcı hatası yok",
                ["Simulation.NoPacketValidationYet"] = "Henüz paket doğrulaması yok",
                ["Simulation.TransmissionError"] = "Aktarım hatası: {0}",
                ["Simulation.NoBuiltPacketsForValidation"] = "Doğrulama için oluşturulmuş haberleşme paketleri yok.",
                ["Simulation.BothBuiltPacketsValid"] = "Oluşturulan iki haberleşme paketi de geçerli.",
                ["Simulation.PacketValidationPair"] = "Paket 1: {0} Paket 2: {1}",
                ["Simulation.FeedbackSendFailed"] = "Geri besleme gönderilemedi: {0}",

                ["Automation.Script"] = "Betik",
                ["Automation.Attaching"] = "Baykar.UserInterface uygulamasına bağlanılıyor...",
                ["Automation.MainWindowNotFound"] = "Baykar.UserInterface ana penceresi bulunamadı.",
                ["Automation.AttachedWindowTitle"] = "Bağlanan pencere başlığı: {0}",
                ["Automation.DefaultScriptNotFoundPrompt"] = "Varsayılan test betiği bulunamadı. Test betiği yolunu girin: ",
                ["Automation.ScriptPathRequired"] = "Test betiği yolu gereklidir.",
                ["Automation.UserInterfaceNotRunning"] = "Baykar.UserInterface çalışmıyor. Otomasyon testlerinden önce başlatın.",
                ["Automation.Test"] = "Test",
                ["Automation.Pass"] = "BAŞARILI",
                ["Automation.Fail"] = "BAŞARISIZ",
                ["Automation.FinalResult"] = "Nihai Sonuç",
                ["Automation.Passed"] = "BAŞARILI",
                ["Automation.Failed"] = "BAŞARISIZ",
                ["Automation.PdfReport"] = "PDF Raporu",
                ["Automation.PdfReportFailed"] = "PDF raporu oluşturulamadı: {0}",
                ["Automation.StepCompleted"] = "Adım tamamlandı.",
                ["Automation.ExpectedTextFound"] = "Beklenen metin bulundu.",
                ["Automation.TextWasNotEmpty"] = "Metin boş değildi.",
                ["Automation.NumericValueGreater"] = "Sayısal değer beklenenden büyüktü.",
                ["Automation.UnsupportedAction"] = "Desteklenmeyen işlem: {0}",
                ["Automation.RequiredProperty"] = "{0} gereklidir.",
                ["Automation.ElementToExist"] = "öğenin var olması",
                ["Automation.NotFound"] = "bulunamadı",
                ["Automation.NonEmptyText"] = "boş olmayan metin",
                ["Automation.NotNumericActual"] = "sayısal değil; metin='{0}'",
                ["Automation.FailureMessage"] = "Adım='{0}', AutomationId='{1}', Beklenen='{2}', Gerçek='{3}', TimeoutMs={4}.",
                ["AutomationStep.Default User Interface Automation Test"] = "Varsayılan Kullanıcı Arayüzü Otomasyon Testi",
                ["AutomationStep.Start user interface listener"] = "Kullanıcı arayüzü dinleyicisini başlat",
                ["AutomationStep.Wait for Communication Packet 1 count"] = "Haberleşme Paketi 1 sayısını bekle",
                ["AutomationStep.Wait for Communication Packet 2 count"] = "Haberleşme Paketi 2 sayısını bekle",
                ["AutomationStep.Send Command 1 and verify feedback"] = "Komut 1 gönder ve geri beslemeyi doğrula",
                ["AutomationStep.Send Setting 1 and verify feedback"] = "Ayar 1 gönder ve geri beslemeyi doğrula",
                ["AutomationStep.Send Command 1"] = "Komut 1 gönder",
                ["AutomationStep.Send Setting 1"] = "Ayar 1 gönder",
                ["AutomationStep.Start logging"] = "Loglamayı başlat",
                ["AutomationStep.Stop logging"] = "Loglamayı durdur",

                ["Report.Title"] = "UI Otomasyon Test Raporu",
                ["Report.TestName"] = "Test adı",
                ["Report.StartTime"] = "Başlangıç zamanı",
                ["Report.FinishTime"] = "Bitiş zamanı",
                ["Report.Duration"] = "Süre",
                ["Report.FinalResult"] = "Nihai sonuç",
                ["Report.StepResults"] = "Adım Sonuçları",
                ["Report.Step"] = "Adım",
                ["Report.Result"] = "Sonuç",
                ["Report.Message"] = "Mesaj",
                ["Report.Passed"] = "Başarılı",
                ["Report.Failed"] = "Başarısız"
            }
        };

    public LocalizationService(SupportedLanguage currentLanguage = SupportedLanguage.English)
    {
        CurrentLanguage = currentLanguage;
    }

    public SupportedLanguage CurrentLanguage { get; private set; }

    public void SetLanguage(SupportedLanguage language)
    {
        CurrentLanguage = language;
    }

    public string GetText(string key)
    {
        IReadOnlyDictionary<string, string> currentTranslations = Translations[CurrentLanguage];

        if (currentTranslations.TryGetValue(key, out string? value))
        {
            return value;
        }

        return Translations[SupportedLanguage.English].TryGetValue(key, out string? fallbackValue)
            ? fallbackValue
            : key;
    }

    public string GetTextOrDefault(string key, string defaultText)
    {
        string value = GetText(key);
        return value == key ? defaultText : value;
    }

    public string FormatText(string key, params object[] values)
    {
        return string.Format(CultureInfo.InvariantCulture, GetText(key), values);
    }

    public string FormatTextOrDefault(string key, string defaultText, params object[] values)
    {
        return string.Format(CultureInfo.InvariantCulture, GetTextOrDefault(key, defaultText), values);
    }

    public static SupportedLanguage FromCode(string? languageCode)
    {
        return string.Equals(languageCode, "tr", StringComparison.OrdinalIgnoreCase)
            ? SupportedLanguage.Turkish
            : SupportedLanguage.English;
    }

    public static string ToCode(SupportedLanguage language)
    {
        return language == SupportedLanguage.Turkish ? "tr" : "en";
    }
}
